# Generated by Django 5.2.3 on 2025-08-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHive_app', '0003_rename_transaction_id_booking_attendee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
