# Generated by Django 5.2.3 on 2025-08-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHive_app', '0004_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
